# Generated by Django 4.1.3 on 2022-11-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermanage',
            table='usermanage',
        ),
    ]
